version: "3.1"
services:

  mysql8:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: ${MYSQL_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/log:/var/log/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - ${PORT_ADMINER}:8080
